name: "Update dataset"
on:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: install dependencies
      run: make deps
    - run: git config --global user.email 'katharinekurz@gmail.com'
    - run: git config --global user.name 'Katharine Kurz'
    - name: update dataset
      run: make update
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: covid-artifacts
        AWS_DEFAULT_REGION: us-east-1
